import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { CreditCard, Wallet, Banknote, X, Check } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { useQueryClient } from "@tanstack/react-query";

interface PaymentProps {
  cartItems: any[];
  onCancel: () => void;
  onSuccess: () => void;
}

export const Payment = ({ cartItems, onCancel, onSuccess }: PaymentProps) => {
  const [customerName, setCustomerName] = useState("");
  const [address, setAddress] = useState("");
  const [contactInfo, setContactInfo] = useState("");
  const [paymentMode, setPaymentMode] = useState("COD");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const queryClient = useQueryClient();

  const total = cartItems.reduce((sum, item) => sum + (item.unit_price * item.quantity), 0);

  const handleConfirmOrder = async () => {
    if (!customerName || !address || !contactInfo) {
      toast.error("Missing information", {
        description: "Please fill in all required fields"
      });
      return;
    }

    setIsSubmitting(true);

    try {
      // Get default warehouse
      const { data: warehouse } = await supabase
        .from("warehouses")
        .select("id")
        .limit(1)
        .single();

      if (!warehouse) {
        throw new Error("No warehouse found");
      }

      // Create customer if doesn't exist
      let customerId = null;
      const { data: existingCustomer } = await supabase
        .from("customers")
        .select("id")
        .eq("customer_name", customerName)
        .maybeSingle();

      if (existingCustomer) {
        customerId = existingCustomer.id;
        
        // Update contact info
        await supabase
          .from("customers")
          .update({ contact_info: `${contactInfo} | ${address}` })
          .eq("id", customerId);
      } else {
        const { data: newCustomer, error: customerError } = await supabase
          .from("customers")
          .insert({
            customer_id: "", // Auto-generated by trigger
            customer_name: customerName,
            contact_info: `${contactInfo} | ${address}`
          })
          .select()
          .single();

        if (customerError) throw customerError;
        customerId = newCustomer.id;
      }

      // Create sales orders for each cart item
      for (const item of cartItems) {
        // Create sales order
        const { data: salesOrder, error: orderError } = await supabase
          .from("sales_orders")
          .insert({
            order_id: "", // Auto-generated by trigger
            customer_id: customerId,
            product_id: item.id,
            demand_quantity: item.quantity,
            total_amount: item.unit_price * item.quantity,
            payment_terms: paymentMode,
            delivery_status: "pending"
          })
          .select()
          .single();

        if (orderError) throw orderError;

        // Deduct inventory
        const { data: inventory } = await supabase
          .from("inventory")
          .select("id, quantity")
          .eq("item_id", item.id)
          .eq("warehouse_id", warehouse.id)
          .single();

        if (inventory) {
          const newQuantity = Math.max(0, inventory.quantity - item.quantity);
          await supabase
            .from("inventory")
            .update({ quantity: newQuantity })
            .eq("id", inventory.id);
        }

        // Create stock transaction
        await supabase
          .from("stock_transactions")
          .insert({
            item_id: item.id,
            warehouse_id: warehouse.id,
            transaction_type: "stock-out",
            quantity: item.quantity,
            reference_number: salesOrder.order_id,
            unit_cost: item.unit_price,
            total_cost: item.unit_price * item.quantity,
            notes: `E-commerce order for ${customerName}`
          });
      }

      toast.success("Order confirmed!", {
        description: "Your order has been placed successfully."
      });

      queryClient.invalidateQueries({ queryKey: ["shop-products"] });
      queryClient.invalidateQueries({ queryKey: ["sales-orders"] });
      queryClient.invalidateQueries({ queryKey: ["receipts"] });
      
      onSuccess();
    } catch (error: any) {
      console.error("Order error:", error);
      toast.error("Order failed", {
        description: error.message || "Failed to process your order. Please try again."
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="mb-8">
        <h2 className="text-3xl font-bold text-foreground mb-2">Payment & Delivery</h2>
        <p className="text-muted-foreground">Complete your order information</p>
      </div>

      <div className="grid lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Customer Information</CardTitle>
              <CardDescription>Please provide your contact details</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="customerName">Customer Name *</Label>
                <Input
                  id="customerName"
                  value={customerName}
                  onChange={(e) => setCustomerName(e.target.value)}
                  placeholder="Enter your full name"
                  required
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="contactInfo">Contact Number *</Label>
                <Input
                  id="contactInfo"
                  value={contactInfo}
                  onChange={(e) => setContactInfo(e.target.value)}
                  placeholder="Enter your phone number"
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="address">Delivery Address *</Label>
                <Textarea
                  id="address"
                  value={address}
                  onChange={(e) => setAddress(e.target.value)}
                  placeholder="Enter complete delivery address"
                  rows={3}
                  required
                />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Payment Method</CardTitle>
              <CardDescription>Select your preferred payment option</CardDescription>
            </CardHeader>
            <CardContent>
              <RadioGroup value={paymentMode} onValueChange={setPaymentMode}>
                <div className="flex items-center space-x-3 p-4 border rounded-lg hover:bg-accent transition-colors cursor-pointer">
                  <RadioGroupItem value="COD" id="cod" />
                  <Label htmlFor="cod" className="flex items-center gap-2 cursor-pointer flex-1">
                    <Banknote className="w-5 h-5 text-primary" />
                    <div>
                      <div className="font-medium">Cash on Delivery</div>
                      <div className="text-sm text-muted-foreground">Pay when you receive your order</div>
                    </div>
                  </Label>
                </div>

                <div className="flex items-center space-x-3 p-4 border rounded-lg hover:bg-accent transition-colors cursor-pointer">
                  <RadioGroupItem value="GCash" id="gcash" />
                  <Label htmlFor="gcash" className="flex items-center gap-2 cursor-pointer flex-1">
                    <Wallet className="w-5 h-5 text-primary" />
                    <div>
                      <div className="font-medium">GCash</div>
                      <div className="text-sm text-muted-foreground">Digital wallet payment</div>
                    </div>
                  </Label>
                </div>

                <div className="flex items-center space-x-3 p-4 border rounded-lg hover:bg-accent transition-colors cursor-pointer">
                  <RadioGroupItem value="Credit Card" id="card" />
                  <Label htmlFor="card" className="flex items-center gap-2 cursor-pointer flex-1">
                    <CreditCard className="w-5 h-5 text-primary" />
                    <div>
                      <div className="font-medium">Credit/Debit Card</div>
                      <div className="text-sm text-muted-foreground">Visa, Mastercard, etc.</div>
                    </div>
                  </Label>
                </div>
              </RadioGroup>
            </CardContent>
          </Card>
        </div>

        <div className="lg:col-span-1">
          <Card className="sticky top-6 border-2 border-primary/20">
            <CardHeader>
              <CardTitle>Order Summary</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                {cartItems.map((item) => (
                  <div key={item.id} className="flex justify-between text-sm">
                    <span className="text-muted-foreground">
                      {item.name} x {item.quantity}
                    </span>
                    <span className="font-medium">
                      ₱{(item.unit_price * item.quantity).toLocaleString()}
                    </span>
                  </div>
                ))}
              </div>

              <div className="h-px bg-border" />

              <div className="flex justify-between items-center">
                <span className="text-lg font-semibold">Total Amount</span>
                <span className="text-2xl font-bold text-primary">
                  ₱{total.toLocaleString()}
                </span>
              </div>

              <div className="pt-2 space-y-2">
                <Button
                  onClick={handleConfirmOrder}
                  disabled={isSubmitting}
                  className="w-full h-12 text-lg"
                  size="lg"
                >
                  <Check className="w-5 h-5 mr-2" />
                  {isSubmitting ? "Processing..." : "Confirm Order"}
                </Button>
                <Button
                  onClick={onCancel}
                  disabled={isSubmitting}
                  variant="outline"
                  className="w-full"
                >
                  <X className="w-4 h-4 mr-2" />
                  Cancel
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};