import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { Search, Plus, Edit } from "lucide-react";
import { format } from "date-fns";

export default function DemandForecasting() {
  const queryClient = useQueryClient();
  const [searchTerm, setSearchTerm] = useState("");
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [selectedForecast, setSelectedForecast] = useState<any>(null);
  const [formData, setFormData] = useState({
    product_id: "",
    lead_time: "",
    predicted_demand: "",
    recommend_order_qty: "",
    notes: "",
  });

  // Fetch forecasts with related data and historical sales
  const { data: forecasts, isLoading } = useQuery({
    queryKey: ["demand_forecasting"],
    queryFn: async () => {
      const { data: forecastData, error } = await supabase
        .from("demand_forecasting")
        .select(`
          *,
          items (id, name, sku)
        `)
        .order("created_at", { ascending: false });

      if (error) throw error;

      // Fetch historical sales for each product
      const forecastsWithSales = await Promise.all(
        (forecastData || []).map(async (forecast) => {
          const { data: transactions } = await supabase
            .from("stock_transactions")
            .select("quantity")
            .eq("item_id", forecast.product_id)
            .eq("transaction_type", "stock-out");

          const historicalSales = transactions?.reduce((sum, t) => sum + Math.abs(t.quantity), 0) || 0;

          return {
            ...forecast,
            historical_sales: historicalSales,
          };
        })
      );

      return forecastsWithSales;
    },
  });

  // Fetch products from inventory
  const { data: products } = useQuery({
    queryKey: ["inventory_items"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("items")
        .select("*")
        .eq("is_active", true)
        .order("name");
      if (error) throw error;
      return data;
    },
  });


  // Create forecast mutation
  const createForecastMutation = useMutation({
    mutationFn: async (data: any) => {
      const { error } = await supabase
        .from("demand_forecasting")
        .insert([{
          forecast_id: "", // Auto-generated by trigger
          product_id: data.product_id,
          lead_time: parseInt(data.lead_time),
          predicted_demand: parseInt(data.predicted_demand),
          recommend_order_qty: parseInt(data.recommend_order_qty),
          notes: data.notes || null,
        }]);

      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("Demand forecast created successfully");
      queryClient.invalidateQueries({ queryKey: ["demand_forecasting"] });
      setIsAddDialogOpen(false);
      resetForm();
    },
    onError: (error: any) => {
      toast.error(`Failed to create forecast: ${error.message}`);
    },
  });

  // Update forecast mutation
  const updateForecastMutation = useMutation({
    mutationFn: async ({ id, data }: any) => {
      const { error } = await supabase
        .from("demand_forecasting")
        .update({
          product_id: data.product_id,
          lead_time: parseInt(data.lead_time),
          predicted_demand: parseInt(data.predicted_demand),
          recommend_order_qty: parseInt(data.recommend_order_qty),
          notes: data.notes || null,
          updated_at: new Date().toISOString(),
        })
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("Demand forecast updated successfully");
      queryClient.invalidateQueries({ queryKey: ["demand_forecasting"] });
      setIsAddDialogOpen(false);
      setSelectedForecast(null);
      resetForm();
    },
    onError: (error: any) => {
      toast.error(`Failed to update forecast: ${error.message}`);
    },
  });

  const resetForm = () => {
    setFormData({
      product_id: "",
      lead_time: "",
      predicted_demand: "",
      recommend_order_qty: "",
      notes: "",
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.product_id || !formData.lead_time || !formData.predicted_demand || !formData.recommend_order_qty) {
      toast.error("Please fill in all required fields");
      return;
    }

    if (selectedForecast) {
      updateForecastMutation.mutate({ id: selectedForecast.id, data: formData });
    } else {
      createForecastMutation.mutate(formData);
    }
  };

  const handleEdit = (forecast: any) => {
    setSelectedForecast(forecast);
    setFormData({
      product_id: forecast.product_id,
      lead_time: forecast.lead_time?.toString() || "",
      predicted_demand: forecast.predicted_demand?.toString() || "",
      recommend_order_qty: forecast.recommend_order_qty?.toString() || "",
      notes: forecast.notes || "",
    });
    setIsAddDialogOpen(true);
  };

  const filteredForecasts = (forecasts || []).filter((forecast) => {
    const search = searchTerm.toLowerCase();
    return (
      forecast.forecast_id?.toLowerCase().includes(search) ||
      forecast.items?.name?.toLowerCase().includes(search)
    );
  });

  if (isLoading) {
    return <div className="flex items-center justify-center h-64">Loading demand forecasts...</div>;
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-foreground">Demand Forecasting</h2>
          <p className="text-sm text-muted-foreground">
            Calculate recommended order quantities based on historical sales and lead time
          </p>
        </div>
        <Button onClick={() => {
          setSelectedForecast(null);
          resetForm();
          setIsAddDialogOpen(true);
        }}>
          <Plus className="h-4 w-4 mr-2" />
          Add New Forecast
        </Button>
      </div>

      {/* Search Bar */}
      <div className="relative max-w-sm">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <Input
          placeholder="Search by Forecast ID or Product..."
          className="pl-9"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      {/* Forecasts Table */}
      <Card>
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Forecast ID</TableHead>
                  <TableHead>Product</TableHead>
                  <TableHead>Historical Sales</TableHead>
                  <TableHead>Lead Time (days)</TableHead>
                  <TableHead>Predicted Demand</TableHead>
                  <TableHead>Recommend Order Qty</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredForecasts.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={7} className="text-center py-8 text-muted-foreground">
                      No demand forecasts found. Create your first forecast to get started.
                    </TableCell>
                  </TableRow>
                ) : (
                  filteredForecasts.map((forecast) => (
                    <TableRow key={forecast.id}>
                      <TableCell className="font-medium">{forecast.forecast_id}</TableCell>
                      <TableCell>{forecast.items?.name || "—"}</TableCell>
                      <TableCell>{forecast.historical_sales || 0} units</TableCell>
                      <TableCell>{forecast.lead_time || 0} days</TableCell>
                      <TableCell>{forecast.predicted_demand || 0} units</TableCell>
                      <TableCell>{forecast.recommend_order_qty || 0} units</TableCell>
                      <TableCell>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleEdit(forecast)}
                        >
                          <Edit className="h-4 w-4" />
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>

      {/* Add/Edit Dialog */}
      <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>
              {selectedForecast ? "Edit Demand Forecast" : "Add New Demand Forecast"}
            </DialogTitle>
            <DialogDescription>
              Calculate recommended order quantity: (Historical Sales / 30) × Lead Time + Buffer (5)
            </DialogDescription>
          </DialogHeader>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              {/* Product */}
              <div className="space-y-2">
                <Label>Product *</Label>
                <Select
                  value={formData.product_id}
                  onValueChange={async (value) => {
                    // Fetch historical sales
                    const { data: transactions } = await supabase
                      .from("stock_transactions")
                      .select("quantity")
                      .eq("item_id", value)
                      .eq("transaction_type", "stock-out");

                    const historicalSales = transactions?.reduce((sum, t) => sum + Math.abs(t.quantity), 0) || 0;
                    
                    setFormData({ ...formData, product_id: value });
                  }}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select product" />
                  </SelectTrigger>
                  <SelectContent>
                    {products?.map((product) => (
                      <SelectItem key={product.id} value={product.id}>
                        {product.name} ({product.sku})
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Lead Time */}
              <div className="space-y-2">
                <Label>Lead Time (days) *</Label>
                <Input
                  type="number"
                  placeholder="Enter lead time in days"
                  value={formData.lead_time}
                  onChange={async (e) => {
                    const leadTime = e.target.value;
                    setFormData({ ...formData, lead_time: leadTime });

                    // Auto-calculate predicted demand if product is selected
                    if (formData.product_id && leadTime) {
                      const { data: transactions } = await supabase
                        .from("stock_transactions")
                        .select("quantity")
                        .eq("item_id", formData.product_id)
                        .eq("transaction_type", "stock-out");

                      const historicalSales = transactions?.reduce((sum, t) => sum + Math.abs(t.quantity), 0) || 0;
                      const predictedDemand = Math.round((historicalSales / 30) * parseInt(leadTime));
                      const recommendQty = predictedDemand + 5; // Buffer of 5

                      setFormData({
                        ...formData,
                        lead_time: leadTime,
                        predicted_demand: predictedDemand.toString(),
                        recommend_order_qty: recommendQty.toString(),
                      });
                    }
                  }}
                />
              </div>

              {/* Predicted Demand (Auto-calculated) */}
              <div className="space-y-2">
                <Label>Predicted Demand (units) *</Label>
                <Input
                  type="number"
                  placeholder="Auto-calculated"
                  value={formData.predicted_demand}
                  readOnly
                  className="bg-muted"
                />
                <p className="text-xs text-muted-foreground">
                  Formula: (Historical Sales / 30) × Lead Time
                </p>
              </div>

              {/* Recommend Order Qty (Auto-calculated) */}
              <div className="space-y-2">
                <Label>Recommend Order Qty (units) *</Label>
                <Input
                  type="number"
                  placeholder="Auto-calculated"
                  value={formData.recommend_order_qty}
                  readOnly
                  className="bg-muted"
                />
                <p className="text-xs text-muted-foreground">
                  Formula: Predicted Demand + Buffer (5)
                </p>
              </div>

              {/* Notes */}
              <div className="space-y-2 col-span-2">
                <Label>Notes</Label>
                <Textarea
                  placeholder="Add any additional notes or observations..."
                  value={formData.notes}
                  onChange={(e) =>
                    setFormData({ ...formData, notes: e.target.value })
                  }
                  rows={3}
                />
              </div>
            </div>

            <div className="flex justify-end space-x-2 pt-4">
              <Button
                type="button"
                variant="outline"
                onClick={() => {
                  setIsAddDialogOpen(false);
                  setSelectedForecast(null);
                  resetForm();
                }}
              >
                Cancel
              </Button>
              <Button
                type="submit"
                disabled={createForecastMutation.isPending || updateForecastMutation.isPending}
              >
                {selectedForecast ? "Update Forecast" : "Save Forecast"}
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
}
