import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { Search, Plus, Edit } from "lucide-react";
import { format } from "date-fns";

export default function DemandForecasting() {
  const queryClient = useQueryClient();
  const [searchTerm, setSearchTerm] = useState("");
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [selectedForecast, setSelectedForecast] = useState<any>(null);
  const [formData, setFormData] = useState({
    product_id: "",
    warehouse_id: "",
    forecast_period_start: "",
    forecast_period_end: "",
    predicted_demand: "",
    actual_demand: "",
    notes: "",
  });

  // Fetch forecasts with related data
  const { data: forecasts, isLoading } = useQuery({
    queryKey: ["demand_forecasting"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("demand_forecasting")
        .select(`
          *,
          items (id, name, sku),
          warehouses (id, name)
        `)
        .order("forecast_period_start", { ascending: false });

      if (error) throw error;
      return data;
    },
  });

  // Fetch products from inventory
  const { data: products } = useQuery({
    queryKey: ["inventory_items"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("items")
        .select("*")
        .eq("is_active", true)
        .order("name");
      if (error) throw error;
      return data;
    },
  });

  // Fetch warehouses from inventory
  const { data: warehouses } = useQuery({
    queryKey: ["warehouses"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("warehouses")
        .select("*")
        .eq("is_active", true)
        .order("name");
      if (error) throw error;
      return data;
    },
  });

  // Create forecast mutation
  const createForecastMutation = useMutation({
    mutationFn: async (data: any) => {
      // Calculate accuracy if actual demand is provided
      let accuracyPercentage = null;
      if (data.actual_demand && data.predicted_demand) {
        const predicted = parseInt(data.predicted_demand);
        const actual = parseInt(data.actual_demand);
        accuracyPercentage = 100 - Math.abs((predicted - actual) / actual * 100);
      }

      const { error } = await supabase
        .from("demand_forecasting")
        .insert([{
          forecast_id: "", // Auto-generated by trigger
          product_id: data.product_id,
          warehouse_id: data.warehouse_id,
          forecast_period_start: data.forecast_period_start,
          forecast_period_end: data.forecast_period_end,
          predicted_demand: parseInt(data.predicted_demand),
          actual_demand: data.actual_demand ? parseInt(data.actual_demand) : null,
          accuracy_percentage: accuracyPercentage,
          notes: data.notes || null,
        }]);

      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("Demand forecast created successfully");
      queryClient.invalidateQueries({ queryKey: ["demand_forecasting"] });
      setIsAddDialogOpen(false);
      resetForm();
    },
    onError: (error: any) => {
      toast.error(`Failed to create forecast: ${error.message}`);
    },
  });

  // Update forecast mutation
  const updateForecastMutation = useMutation({
    mutationFn: async ({ id, data }: any) => {
      // Recalculate accuracy
      let accuracyPercentage = null;
      if (data.actual_demand && data.predicted_demand) {
        const predicted = parseInt(data.predicted_demand);
        const actual = parseInt(data.actual_demand);
        accuracyPercentage = 100 - Math.abs((predicted - actual) / actual * 100);
      }

      const { error } = await supabase
        .from("demand_forecasting")
        .update({
          product_id: data.product_id,
          warehouse_id: data.warehouse_id,
          forecast_period_start: data.forecast_period_start,
          forecast_period_end: data.forecast_period_end,
          predicted_demand: parseInt(data.predicted_demand),
          actual_demand: data.actual_demand ? parseInt(data.actual_demand) : null,
          accuracy_percentage: accuracyPercentage,
          notes: data.notes || null,
          updated_at: new Date().toISOString(),
        })
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("Demand forecast updated successfully");
      queryClient.invalidateQueries({ queryKey: ["demand_forecasting"] });
      setIsAddDialogOpen(false);
      setSelectedForecast(null);
      resetForm();
    },
    onError: (error: any) => {
      toast.error(`Failed to update forecast: ${error.message}`);
    },
  });

  const resetForm = () => {
    setFormData({
      product_id: "",
      warehouse_id: "",
      forecast_period_start: "",
      forecast_period_end: "",
      predicted_demand: "",
      actual_demand: "",
      notes: "",
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.product_id || !formData.warehouse_id || !formData.forecast_period_start || 
        !formData.forecast_period_end || !formData.predicted_demand) {
      toast.error("Please fill in all required fields");
      return;
    }

    if (selectedForecast) {
      updateForecastMutation.mutate({ id: selectedForecast.id, data: formData });
    } else {
      createForecastMutation.mutate(formData);
    }
  };

  const handleEdit = (forecast: any) => {
    setSelectedForecast(forecast);
    setFormData({
      product_id: forecast.product_id,
      warehouse_id: forecast.warehouse_id,
      forecast_period_start: forecast.forecast_period_start,
      forecast_period_end: forecast.forecast_period_end,
      predicted_demand: forecast.predicted_demand.toString(),
      actual_demand: forecast.actual_demand?.toString() || "",
      notes: forecast.notes || "",
    });
    setIsAddDialogOpen(true);
  };

  const filteredForecasts = (forecasts || []).filter((forecast) => {
    const search = searchTerm.toLowerCase();
    return (
      forecast.forecast_id?.toLowerCase().includes(search) ||
      forecast.items?.name?.toLowerCase().includes(search) ||
      forecast.warehouses?.name?.toLowerCase().includes(search)
    );
  });

  const getAccuracyBadge = (accuracy: number | null) => {
    if (accuracy === null) return <Badge variant="outline">Pending</Badge>;
    if (accuracy >= 90) return <Badge variant="default">Excellent ({accuracy.toFixed(1)}%)</Badge>;
    if (accuracy >= 75) return <Badge variant="secondary">Good ({accuracy.toFixed(1)}%)</Badge>;
    return <Badge variant="destructive">Poor ({accuracy.toFixed(1)}%)</Badge>;
  };

  if (isLoading) {
    return <div className="flex items-center justify-center h-64">Loading demand forecasts...</div>;
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-foreground">Demand Forecasting</h2>
          <p className="text-sm text-muted-foreground">
            Predict future demand based on historical data and market trends
          </p>
        </div>
        <Button onClick={() => {
          setSelectedForecast(null);
          resetForm();
          setIsAddDialogOpen(true);
        }}>
          <Plus className="h-4 w-4 mr-2" />
          Add New Forecast
        </Button>
      </div>

      {/* Search Bar */}
      <div className="relative max-w-sm">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <Input
          placeholder="Search by Forecast ID, Product, or Warehouse..."
          className="pl-9"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      {/* Forecasts Table */}
      <Card>
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Forecast ID</TableHead>
                  <TableHead>Product</TableHead>
                  <TableHead>Warehouse</TableHead>
                  <TableHead>Period</TableHead>
                  <TableHead>Predicted Demand</TableHead>
                  <TableHead>Actual Demand</TableHead>
                  <TableHead>Accuracy</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredForecasts.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={8} className="text-center py-8 text-muted-foreground">
                      No demand forecasts found. Create your first forecast to get started.
                    </TableCell>
                  </TableRow>
                ) : (
                  filteredForecasts.map((forecast) => (
                    <TableRow key={forecast.id}>
                      <TableCell className="font-medium">{forecast.forecast_id}</TableCell>
                      <TableCell>{forecast.items?.name || "—"}</TableCell>
                      <TableCell>{forecast.warehouses?.name || "—"}</TableCell>
                      <TableCell>
                        {format(new Date(forecast.forecast_period_start), "MMM dd")} - {format(new Date(forecast.forecast_period_end), "MMM dd, yyyy")}
                      </TableCell>
                      <TableCell>{forecast.predicted_demand} units</TableCell>
                      <TableCell>{forecast.actual_demand ? `${forecast.actual_demand} units` : "—"}</TableCell>
                      <TableCell>{getAccuracyBadge(forecast.accuracy_percentage)}</TableCell>
                      <TableCell>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleEdit(forecast)}
                        >
                          <Edit className="h-4 w-4" />
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>

      {/* Add/Edit Dialog */}
      <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>
              {selectedForecast ? "Edit Demand Forecast" : "Add New Demand Forecast"}
            </DialogTitle>
            <DialogDescription>
              Create a forecast for future product demand based on historical trends
            </DialogDescription>
          </DialogHeader>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              {/* Product */}
              <div className="space-y-2">
                <Label>Product *</Label>
                <Select
                  value={formData.product_id}
                  onValueChange={(value) =>
                    setFormData({ ...formData, product_id: value })
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select product" />
                  </SelectTrigger>
                  <SelectContent>
                    {products?.map((product) => (
                      <SelectItem key={product.id} value={product.id}>
                        {product.name} ({product.sku})
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Warehouse */}
              <div className="space-y-2">
                <Label>Warehouse *</Label>
                <Select
                  value={formData.warehouse_id}
                  onValueChange={(value) =>
                    setFormData({ ...formData, warehouse_id: value })
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select warehouse" />
                  </SelectTrigger>
                  <SelectContent>
                    {warehouses?.map((warehouse) => (
                      <SelectItem key={warehouse.id} value={warehouse.id}>
                        {warehouse.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Forecast Period Start */}
              <div className="space-y-2">
                <Label>Forecast Period Start *</Label>
                <Input
                  type="date"
                  value={formData.forecast_period_start}
                  onChange={(e) =>
                    setFormData({ ...formData, forecast_period_start: e.target.value })
                  }
                />
              </div>

              {/* Forecast Period End */}
              <div className="space-y-2">
                <Label>Forecast Period End *</Label>
                <Input
                  type="date"
                  value={formData.forecast_period_end}
                  onChange={(e) =>
                    setFormData({ ...formData, forecast_period_end: e.target.value })
                  }
                />
              </div>

              {/* Predicted Demand */}
              <div className="space-y-2">
                <Label>Predicted Demand (units) *</Label>
                <Input
                  type="number"
                  placeholder="Enter predicted demand"
                  value={formData.predicted_demand}
                  onChange={(e) =>
                    setFormData({ ...formData, predicted_demand: e.target.value })
                  }
                />
              </div>

              {/* Actual Demand */}
              <div className="space-y-2">
                <Label>Actual Demand (units)</Label>
                <Input
                  type="number"
                  placeholder="Enter actual demand (optional)"
                  value={formData.actual_demand}
                  onChange={(e) =>
                    setFormData({ ...formData, actual_demand: e.target.value })
                  }
                />
              </div>

              {/* Notes */}
              <div className="space-y-2 col-span-2">
                <Label>Notes</Label>
                <Textarea
                  placeholder="Add any additional notes or observations..."
                  value={formData.notes}
                  onChange={(e) =>
                    setFormData({ ...formData, notes: e.target.value })
                  }
                  rows={3}
                />
              </div>
            </div>

            <div className="flex justify-end space-x-2 pt-4">
              <Button
                type="button"
                variant="outline"
                onClick={() => {
                  setIsAddDialogOpen(false);
                  setSelectedForecast(null);
                  resetForm();
                }}
              >
                Cancel
              </Button>
              <Button
                type="submit"
                disabled={createForecastMutation.isPending || updateForecastMutation.isPending}
              >
                {selectedForecast ? "Update Forecast" : "Save Forecast"}
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
}
