import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Card, CardContent } from "@/components/ui/card";
import { toast } from "sonner";
import { Search, Plus, Edit } from "lucide-react";

export default function DemandForecasting() {
  const queryClient = useQueryClient();
  const [searchTerm, setSearchTerm] = useState("");
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [selectedForecast, setSelectedForecast] = useState<any>(null);
  const [formData, setFormData] = useState({
    product_id: "",
    plan_id: "",
    lead_time: "",
    notes: "",
  });
  const [historicalSales, setHistoricalSales] = useState(0);

  // Fetch forecasts with related data
  const { data: forecasts, isLoading } = useQuery({
    queryKey: ["demand_forecasting"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("demand_forecasting")
        .select(`
          *,
          items (id, name, sku)
        `)
        .order("created_at", { ascending: false });

      if (error) throw error;

      // Fetch historical sales for each forecast
      const enrichedForecasts = await Promise.all(
        (data || []).map(async (forecast) => {
          const { data: stockData } = await supabase
            .from("stock_transactions")
            .select("quantity")
            .eq("item_id", forecast.product_id)
            .eq("transaction_type", "stock-out");

          // Sum the actual quantity values from stock_transactions
          const totalSales = stockData?.reduce((sum, trans) => sum + trans.quantity, 0) || 0;

          return {
            ...forecast,
            historical_sales: Math.abs(totalSales), // Use absolute value for display
          };
        })
      );

      return enrichedForecasts;
    },
  });

  // Fetch products
  const { data: products } = useQuery({
    queryKey: ["items_list"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("items")
        .select("*")
        .eq("is_active", true)
        .order("name");
      if (error) throw error;
      return data;
    },
  });

  // Fetch supply chain plans with product details
  const { data: supplyChainPlans } = useQuery({
    queryKey: ["supply_chain_plans_list"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("supply_chain_plans")
        .select(`
          plan_id, 
          id, 
          product_id,
          items (id, name, sku)
        `)
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data;
    },
  });

  // Create forecast mutation
  const createForecastMutation = useMutation({
    mutationFn: async (data: any) => {
      const leadTime = parseInt(data.lead_time);
      const predictedDemand = Math.round((historicalSales / 30) * leadTime);
      const recommendOrderQty = predictedDemand + 5; // buffer of 5

      const { error } = await supabase.from("demand_forecasting").insert([
        {
          forecast_id: "", // Auto-generated by trigger
          product_id: data.product_id,
          plan_id: data.plan_id || null,
          lead_time: leadTime,
          predicted_demand: predictedDemand,
          recommend_order_qty: recommendOrderQty,
          notes: data.notes,
        },
      ]);

      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("Demand forecast created successfully");
      queryClient.invalidateQueries({ queryKey: ["demand_forecasting"] });
      queryClient.invalidateQueries({ queryKey: ["supply_chain_plans"] });
      setIsAddDialogOpen(false);
      resetForm();
    },
    onError: (error: any) => {
      toast.error(`Failed to create forecast: ${error.message}`);
    },
  });

  // Update forecast mutation
  const updateForecastMutation = useMutation({
    mutationFn: async ({ id, data }: any) => {
      const leadTime = parseInt(data.lead_time);
      const predictedDemand = Math.round((historicalSales / 30) * leadTime);
      const recommendOrderQty = predictedDemand + 5;

      const { error } = await supabase
        .from("demand_forecasting")
        .update({
          plan_id: data.plan_id || null,
          lead_time: leadTime,
          predicted_demand: predictedDemand,
          recommend_order_qty: recommendOrderQty,
          notes: data.notes,
        })
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("Demand forecast updated successfully");
      queryClient.invalidateQueries({ queryKey: ["demand_forecasting"] });
      queryClient.invalidateQueries({ queryKey: ["supply_chain_plans"] });
      setIsAddDialogOpen(false);
      setSelectedForecast(null);
      resetForm();
    },
    onError: (error: any) => {
      toast.error(`Failed to update forecast: ${error.message}`);
    },
  });

  const resetForm = () => {
    setFormData({
      product_id: "",
      plan_id: "",
      lead_time: "",
      notes: "",
    });
    setHistoricalSales(0);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!formData.product_id || !formData.lead_time) {
      toast.error("Please fill in all required fields");
      return;
    }

    if (selectedForecast) {
      updateForecastMutation.mutate({ id: selectedForecast.id, data: formData });
    } else {
      createForecastMutation.mutate(formData);
    }
  };

  const handleEdit = async (forecast: any) => {
    setSelectedForecast(forecast);
    setHistoricalSales(forecast.historical_sales);
    setFormData({
      product_id: forecast.product_id,
      plan_id: forecast.plan_id || "",
      lead_time: forecast.lead_time?.toString() || "",
      notes: forecast.notes || "",
    });
    setIsAddDialogOpen(true);
  };

  const handlePlanChange = async (planId: string) => {
    setFormData({ ...formData, plan_id: planId });
    
    // Find the plan and auto-populate product
    const selectedPlan = supplyChainPlans?.find(plan => plan.plan_id === planId);
    if (selectedPlan && selectedPlan.product_id) {
      // Auto-populate product
      setFormData(prev => ({ 
        ...prev, 
        plan_id: planId, 
        product_id: selectedPlan.product_id 
      }));
      
      // Fetch historical sales for the selected product
      const { data: stockData } = await supabase
        .from("stock_transactions")
        .select("quantity")
        .eq("item_id", selectedPlan.product_id)
        .eq("transaction_type", "stock-out");

      // Sum the actual quantity values
      const totalSales = stockData?.reduce((sum, trans) => sum + trans.quantity, 0) || 0;
      setHistoricalSales(Math.abs(totalSales));
    }
  };

  const handleProductChange = async (productId: string) => {
    setFormData({ ...formData, product_id: productId });
    
    // Fetch historical sales for the selected product
    const { data: stockData } = await supabase
      .from("stock_transactions")
      .select("quantity")
      .eq("item_id", productId)
      .eq("transaction_type", "stock-out");

    // Sum the actual quantity values
    const totalSales = stockData?.reduce((sum, trans) => sum + trans.quantity, 0) || 0;
    setHistoricalSales(Math.abs(totalSales));
  };

  const filteredForecasts = (forecasts || []).filter((forecast) => {
    const search = searchTerm.toLowerCase();
    return (
      forecast.forecast_id?.toLowerCase().includes(search) ||
      forecast.plan_id?.toLowerCase().includes(search) ||
      forecast.items?.name?.toLowerCase().includes(search)
    );
  });

  const predictedDemand = formData.lead_time ? Math.round((historicalSales / 30) * parseInt(formData.lead_time)) : 0;
  const recommendOrderQty = predictedDemand + 5;

  if (isLoading) {
    return <div className="flex items-center justify-center h-64">Loading demand forecasts...</div>;
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-foreground">Demand Forecasting</h2>
          <p className="text-sm text-muted-foreground">
            Predict demand and calculate recommended order quantities
          </p>
        </div>
        <Button
          onClick={() => {
            setSelectedForecast(null);
            resetForm();
            setIsAddDialogOpen(true);
          }}
        >
          <Plus className="h-4 w-4 mr-2" />
          Add New Forecast
        </Button>
      </div>

      {/* Search Bar */}
      <div className="relative max-w-sm">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <Input
          placeholder="Search by Forecast ID, Plan ID, or Product..."
          className="pl-9"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      {/* Forecasts Table */}
      <Card>
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Forecast ID</TableHead>
                  <TableHead>Plan ID</TableHead>
                  <TableHead>Product (from Plan)</TableHead>
                  <TableHead>Lead Time (days)</TableHead>
                  <TableHead>Predicted Demand</TableHead>
                  <TableHead>Recommend Order Qty</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredForecasts.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={7} className="text-center py-8 text-muted-foreground">
                      No demand forecasts found. Create your first forecast to get started.
                    </TableCell>
                  </TableRow>
                ) : (
                  filteredForecasts.map((forecast) => (
                    <TableRow key={forecast.id}>
                      <TableCell className="font-medium">{forecast.forecast_id}</TableCell>
                      <TableCell>{forecast.plan_id || "—"}</TableCell>
                      <TableCell>{forecast.items?.name || "—"}</TableCell>
                      <TableCell>{forecast.lead_time || "—"}</TableCell>
                      <TableCell>{forecast.predicted_demand} units</TableCell>
                      <TableCell>{forecast.recommend_order_qty || "—"} units</TableCell>
                      <TableCell>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleEdit(forecast)}
                        >
                          <Edit className="h-4 w-4" />
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>

      {/* Add/Edit Dialog */}
      <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>
              {selectedForecast ? "Edit Demand Forecast" : "Add New Demand Forecast"}
            </DialogTitle>
            <DialogDescription>
              Select a plan to auto-populate the product, then enter lead time to calculate predicted demand
            </DialogDescription>
          </DialogHeader>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              {/* Plan ID */}
              <div className="space-y-2">
                <Label>Plan ID</Label>
                <Select
                  value={formData.plan_id}
                  onValueChange={handlePlanChange}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select plan (will auto-fill product)" />
                  </SelectTrigger>
                  <SelectContent>
                    {supplyChainPlans?.map((plan) => (
                      <SelectItem key={plan.id} value={plan.plan_id}>
                        {plan.plan_id} - {plan.items?.name || "No product"}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Product (Auto-populated) */}
              <div className="space-y-2">
                <Label>Product (Auto-populated from Plan)</Label>
                <Input
                  value={
                    formData.product_id && products
                      ? products.find(p => p.id === formData.product_id)?.name || "Not selected"
                      : "Select a plan first"
                  }
                  disabled
                  className="bg-muted"
                />
              </div>

              {/* Historical Sales (Display Only) */}
              <div className="space-y-2">
                <Label>Historical Sales</Label>
                <Input
                  value={`${historicalSales} units`}
                  disabled
                  className="bg-muted"
                />
              </div>

              {/* Lead Time */}
              <div className="space-y-2">
                <Label>Lead Time (days) *</Label>
                <Input
                  type="number"
                  placeholder="Enter lead time"
                  value={formData.lead_time}
                  onChange={(e) => setFormData({ ...formData, lead_time: e.target.value })}
                />
              </div>

              {/* Predicted Demand (Display Only) */}
              <div className="space-y-2">
                <Label>Predicted Demand</Label>
                <Input
                  value={`${predictedDemand} units`}
                  disabled
                  className="bg-muted"
                />
                <p className="text-xs text-muted-foreground">
                  Formula: (Historical Sales / 30) × Lead Time
                </p>
              </div>

              {/* Recommend Order Qty (Display Only) */}
              <div className="space-y-2">
                <Label>Recommend Order Qty</Label>
                <Input
                  value={`${recommendOrderQty} units`}
                  disabled
                  className="bg-muted"
                />
                <p className="text-xs text-muted-foreground">
                  Formula: Predicted Demand + Buffer (5 units)
                </p>
              </div>

              {/* Notes */}
              <div className="space-y-2 col-span-2">
                <Label>Notes</Label>
                <Textarea
                  placeholder="Enter additional notes"
                  value={formData.notes}
                  onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                  rows={3}
                />
              </div>
            </div>

            <div className="flex justify-end space-x-2 pt-4">
              <Button
                type="button"
                variant="outline"
                onClick={() => {
                  setIsAddDialogOpen(false);
                  setSelectedForecast(null);
                  resetForm();
                }}
              >
                Cancel
              </Button>
              <Button
                type="submit"
                disabled={createForecastMutation.isPending || updateForecastMutation.isPending}
              >
                {selectedForecast ? "Update Forecast" : "Save Forecast"}
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
}