import { useState, useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { Search, Plus, Edit, Trash2 } from "lucide-react";

export default function RoutingManagement() {
  const queryClient = useQueryClient();
  const [searchTerm, setSearchTerm] = useState("");
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [selectedRoute, setSelectedRoute] = useState<any>(null);
  const [formData, setFormData] = useState({
    plan_id: "",
    source_warehouse_id: "",
    destination_supplier_id: "",
    distance_km: "",
    vehicle_assigned: "",
    route_status: "scheduled",
    departure_time: "",
    expected_arrival_time: "",
  });

  // Fetch routing management records
  const { data: routes, isLoading } = useQuery({
    queryKey: ["routing_management"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("routing_management")
        .select(`
          *,
          warehouses (id, name),
          suppliers (id, name),
          supply_chain_plans (plan_id, plan_status)
        `)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data;
    },
  });

  // Fetch ONLY APPROVED supply chain plans
  const { data: supplyChainPlans } = useQuery({
    queryKey: ["approved_supply_chain_plans"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("supply_chain_plans")
        .select("plan_id, id, plan_status")
        .eq("plan_status", "approved") // Only fetch approved plans
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data;
    },
  });

  // Fetch warehouses
  const { data: warehouses } = useQuery({
    queryKey: ["warehouses"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("warehouses")
        .select("*")
        .eq("is_active", true)
        .order("name");
      if (error) throw error;
      return data;
    },
  });

  // Fetch suppliers
  const { data: suppliers } = useQuery({
    queryKey: ["suppliers"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("suppliers")
        .select("*")
        .order("name");
      if (error) throw error;
      return data;
    },
  });

  // Create route mutation
  const createRouteMutation = useMutation({
    mutationFn: async (data: any) => {
      const { error } = await supabase.from("routing_management").insert([
        {
          route_id: "", // Auto-generated by trigger
          plan_id: data.plan_id,
          source_warehouse_id: data.source_warehouse_id,
          destination_supplier_id: data.destination_supplier_id,
          distance_km: parseFloat(data.distance_km),
          vehicle_assigned: data.vehicle_assigned,
          route_status: data.route_status,
          departure_time: data.departure_time || null,
          expected_arrival_time: data.expected_arrival_time || null,
        },
      ]);

      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("Route created successfully");
      queryClient.invalidateQueries({ queryKey: ["routing_management"] });
      queryClient.invalidateQueries({ queryKey: ["purchase_orders"] });
      setIsAddDialogOpen(false);
      resetForm();
    },
    onError: (error: any) => {
      toast.error(`Failed to create route: ${error.message}`);
    },
  });

  // Update route mutation
  const updateRouteMutation = useMutation({
    mutationFn: async ({ id, data }: any) => {
      const { error } = await supabase
        .from("routing_management")
        .update({
          source_warehouse_id: data.source_warehouse_id,
          destination_supplier_id: data.destination_supplier_id,
          distance_km: parseFloat(data.distance_km),
          vehicle_assigned: data.vehicle_assigned,
          route_status: data.route_status,
          departure_time: data.departure_time || null,
          expected_arrival_time: data.expected_arrival_time || null,
        })
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("Route updated successfully");
      queryClient.invalidateQueries({ queryKey: ["routing_management"] });
      queryClient.invalidateQueries({ queryKey: ["purchase_orders"] });
      setIsAddDialogOpen(false);
      setSelectedRoute(null);
      resetForm();
    },
    onError: (error: any) => {
      toast.error(`Failed to update route: ${error.message}`);
    },
  });

  // Delete route mutation
  const deleteRouteMutation = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("routing_management")
        .delete()
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("Route deleted successfully");
      queryClient.invalidateQueries({ queryKey: ["routing_management"] });
    },
    onError: (error: any) => {
      toast.error(`Failed to delete route: ${error.message}`);
    },
  });

  const resetForm = () => {
    setFormData({
      plan_id: "",
      source_warehouse_id: "",
      destination_supplier_id: "",
      distance_km: "",
      vehicle_assigned: "",
      route_status: "scheduled",
      departure_time: "",
      expected_arrival_time: "",
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!formData.plan_id || !formData.source_warehouse_id || !formData.destination_supplier_id || !formData.distance_km) {
      toast.error("Please fill in all required fields");
      return;
    }

    if (selectedRoute) {
      updateRouteMutation.mutate({ id: selectedRoute.id, data: formData });
    } else {
      createRouteMutation.mutate(formData);
    }
  };

  const handleEdit = (route: any) => {
    setSelectedRoute(route);
    setFormData({
      plan_id: route.plan_id || "",
      source_warehouse_id: route.source_warehouse_id,
      destination_supplier_id: route.destination_supplier_id,
      distance_km: route.distance_km?.toString() || "",
      vehicle_assigned: route.vehicle_assigned || "",
      route_status: route.route_status,
      departure_time: route.departure_time || "",
      expected_arrival_time: route.expected_arrival_time || "",
    });
    setIsAddDialogOpen(true);
  };

  const handleDelete = (routeId: string) => {
    if (window.confirm("Are you sure you want to delete this route?")) {
      deleteRouteMutation.mutate(routeId);
    }
  };

  const filteredRoutes = (routes || []).filter((route) => {
    const search = searchTerm.toLowerCase();
    return (
      route.route_id?.toLowerCase().includes(search) ||
      route.plan_id?.toLowerCase().includes(search) ||
      route.vehicle_assigned?.toLowerCase().includes(search)
    );
  });

  const getStatusBadge = (status: string) => {
    const variants: Record<string, any> = {
      scheduled: "secondary",
      "in transit": "default",
      delivered: "outline",
      delayed: "destructive",
    };
    return <Badge variant={variants[status] || "outline"}>{status}</Badge>;
  };

  if (isLoading) {
    return <div className="flex items-center justify-center h-64">Loading routes...</div>;
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-foreground">Routing Management</h2>
          <p className="text-sm text-muted-foreground">
            Manage delivery routes and track shipment status
          </p>
        </div>
        <Button
          onClick={() => {
            setSelectedRoute(null);
            resetForm();
            setIsAddDialogOpen(true);
          }}
        >
          <Plus className="h-4 w-4 mr-2" />
          Add New Route
        </Button>
      </div>

      {/* Search Bar */}
      <div className="relative max-w-sm">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <Input
          placeholder="Search by Route ID, Plan ID, or Vehicle..."
          className="pl-9"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      {/* Routes Table */}
      <Card>
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Route ID</TableHead>
                  <TableHead>Plan ID</TableHead>
                  <TableHead>From Warehouse</TableHead>
                  <TableHead>To Supplier</TableHead>
                  <TableHead>Distance (km)</TableHead>
                  <TableHead>Vehicle</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Departure</TableHead>
                  <TableHead>Expected Arrival</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredRoutes.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={10} className="text-center py-8 text-muted-foreground">
                      No routes found. Create your first route to get started.
                    </TableCell>
                  </TableRow>
                ) : (
                  filteredRoutes.map((route) => (
                    <TableRow key={route.id}>
                      <TableCell className="font-medium">{route.route_id}</TableCell>
                      <TableCell>{route.plan_id || "—"}</TableCell>
                      <TableCell>{route.warehouses?.name || "—"}</TableCell>
                      <TableCell>{route.suppliers?.name || "—"}</TableCell>
                      <TableCell>{route.distance_km} km</TableCell>
                      <TableCell>{route.vehicle_assigned || "—"}</TableCell>
                      <TableCell>{getStatusBadge(route.route_status)}</TableCell>
                      <TableCell>{route.departure_time ? new Date(route.departure_time).toLocaleString() : "—"}</TableCell>
                      <TableCell>{route.expected_arrival_time ? new Date(route.expected_arrival_time).toLocaleString() : "—"}</TableCell>
                      <TableCell>
                        <div className="flex gap-2">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleEdit(route)}
                          >
                            <Edit className="h-4 w-4" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleDelete(route.id)}
                          >
                            <Trash2 className="h-4 w-4 text-destructive" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>

      {/* Add/Edit Dialog */}
      <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>
              {selectedRoute ? "Edit Route" : "Add New Route"}
            </DialogTitle>
            <DialogDescription>
              Select an approved plan and configure the route details
            </DialogDescription>
          </DialogHeader>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              {/* Plan ID */}
              <div className="space-y-2">
                <Label>Plan ID (Approved Plans Only) *</Label>
                <Select
                  value={formData.plan_id}
                  onValueChange={(value) => setFormData({ ...formData, plan_id: value })}
                  disabled={!!selectedRoute}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select approved plan" />
                  </SelectTrigger>
                  <SelectContent>
                    {supplyChainPlans?.map((plan) => (
                      <SelectItem key={plan.id} value={plan.plan_id}>
                        {plan.plan_id}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <p className="text-xs text-muted-foreground">
                  Only approved supply chain plans can be routed
                </p>
              </div>

              {/* Source Warehouse */}
              <div className="space-y-2">
                <Label>Source Warehouse *</Label>
                <Select
                  value={formData.source_warehouse_id}
                  onValueChange={(value) => setFormData({ ...formData, source_warehouse_id: value })}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select warehouse" />
                  </SelectTrigger>
                  <SelectContent>
                    {warehouses?.map((warehouse) => (
                      <SelectItem key={warehouse.id} value={warehouse.id}>
                        {warehouse.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Destination Supplier */}
              <div className="space-y-2">
                <Label>Destination Supplier *</Label>
                <Select
                  value={formData.destination_supplier_id}
                  onValueChange={(value) => setFormData({ ...formData, destination_supplier_id: value })}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select supplier" />
                  </SelectTrigger>
                  <SelectContent>
                    {suppliers?.map((supplier) => (
                      <SelectItem key={supplier.id} value={supplier.id}>
                        {supplier.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Distance */}
              <div className="space-y-2">
                <Label>Distance (km) *</Label>
                <Input
                  type="number"
                  step="0.1"
                  placeholder="Enter distance"
                  value={formData.distance_km}
                  onChange={(e) => setFormData({ ...formData, distance_km: e.target.value })}
                />
              </div>

              {/* Vehicle Assigned */}
              <div className="space-y-2">
                <Label>Vehicle Assigned</Label>
                <Input
                  placeholder="e.g., Truck A123"
                  value={formData.vehicle_assigned}
                  onChange={(e) => setFormData({ ...formData, vehicle_assigned: e.target.value })}
                />
              </div>

              {/* Route Status */}
              <div className="space-y-2">
                <Label>Route Status *</Label>
                <Select
                  value={formData.route_status}
                  onValueChange={(value) => setFormData({ ...formData, route_status: value })}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="scheduled">Scheduled</SelectItem>
                    <SelectItem value="in transit">In Transit</SelectItem>
                    <SelectItem value="delivered">Delivered</SelectItem>
                    <SelectItem value="delayed">Delayed</SelectItem>
                  </SelectContent>
                </Select>
                <p className="text-xs text-muted-foreground">
                  Status changes will update related purchase orders
                </p>
              </div>

              {/* Departure Time */}
              <div className="space-y-2">
                <Label>Departure Time</Label>
                <Input
                  type="datetime-local"
                  value={formData.departure_time}
                  onChange={(e) => setFormData({ ...formData, departure_time: e.target.value })}
                />
              </div>

              {/* Expected Arrival Time */}
              <div className="space-y-2">
                <Label>Expected Arrival Time</Label>
                <Input
                  type="datetime-local"
                  value={formData.expected_arrival_time}
                  onChange={(e) => setFormData({ ...formData, expected_arrival_time: e.target.value })}
                />
              </div>
            </div>

            <div className="flex justify-end space-x-2 pt-4">
              <Button
                type="button"
                variant="outline"
                onClick={() => {
                  setIsAddDialogOpen(false);
                  setSelectedRoute(null);
                  resetForm();
                }}
              >
                Cancel
              </Button>
              <Button
                type="submit"
                disabled={createRouteMutation.isPending || updateRouteMutation.isPending}
              >
                {selectedRoute ? "Update Route" : "Save Route"}
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
}