import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { Search, Plus, Eye } from "lucide-react";
import { format } from "date-fns";

export default function RoutingManagement() {
  const queryClient = useQueryClient();
  const [searchTerm, setSearchTerm] = useState("");
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [isViewDialogOpen, setIsViewDialogOpen] = useState(false);
  const [selectedRoute, setSelectedRoute] = useState<any>(null);
  const [formData, setFormData] = useState({
    plan_id: "",
    source_warehouse_id: "",
    destination_supplier_id: "",
    distance_km: "",
    vehicle_assigned: "",
    departure_time: "",
    expected_arrival_time: "",
    route_status: "scheduled",
  });

  // Fetch routes with related data
  const { data: routes, isLoading } = useQuery({
    queryKey: ["routing_management"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("routing_management")
        .select(`
          *,
          warehouses!routing_management_source_warehouse_id_fkey (id, name, address),
          suppliers (id, name, address)
        `)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data;
    },
  });

  // Fetch warehouses from inventory
  const { data: warehouses } = useQuery({
    queryKey: ["warehouses"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("warehouses")
        .select("*")
        .eq("is_active", true)
        .order("name");
      if (error) throw error;
      return data;
    },
  });

  // Fetch suppliers from procurement
  const { data: suppliers } = useQuery({
    queryKey: ["suppliers"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("suppliers")
        .select("*")
        .order("name");
      if (error) throw error;
      return data;
    },
  });

  // Create route mutation
  const createRouteMutation = useMutation({
    mutationFn: async (data: any) => {
      const { error} = await supabase
        .from("routing_management")
        .insert([{
          route_id: "", // Auto-generated by trigger
          plan_id: data.plan_id || null,
          source_warehouse_id: data.source_warehouse_id,
          destination_supplier_id: data.destination_supplier_id,
          distance_km: data.distance_km ? parseFloat(data.distance_km) : null,
          vehicle_assigned: data.vehicle_assigned || null,
          departure_time: data.departure_time || null,
          expected_arrival_time: data.expected_arrival_time || null,
          route_status: data.route_status,
        }]);

      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("Route created successfully");
      queryClient.invalidateQueries({ queryKey: ["routing_management"] });
      setIsAddDialogOpen(false);
      resetForm();
    },
    onError: (error: any) => {
      toast.error(`Failed to create route: ${error.message}`);
    },
  });

  const resetForm = () => {
    setFormData({
      plan_id: "",
      source_warehouse_id: "",
      destination_supplier_id: "",
      distance_km: "",
      vehicle_assigned: "",
      departure_time: "",
      expected_arrival_time: "",
      route_status: "scheduled",
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.source_warehouse_id || !formData.destination_supplier_id) {
      toast.error("Please select source warehouse and destination supplier");
      return;
    }

    createRouteMutation.mutate(formData);
  };

  const filteredRoutes = (routes || []).filter((route) => {
    const search = searchTerm.toLowerCase();
    return (
      route.route_id?.toLowerCase().includes(search) ||
      route.warehouses?.name?.toLowerCase().includes(search) ||
      route.suppliers?.name?.toLowerCase().includes(search)
    );
  });

  const getStatusBadge = (status: string) => {
    const variants: Record<string, any> = {
      scheduled: "secondary",
      in_transit: "default",
      delivered: "outline",
      delayed: "destructive",
    };
    return <Badge variant={variants[status] || "outline"}>{status}</Badge>;
  };

  if (isLoading) {
    return <div className="flex items-center justify-center h-64">Loading routes...</div>;
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-foreground">Routing Management</h2>
          <p className="text-sm text-muted-foreground">
            Manage routes between warehouses and suppliers
          </p>
        </div>
        <Button onClick={() => {
          resetForm();
          setIsAddDialogOpen(true);
        }}>
          <Plus className="h-4 w-4 mr-2" />
          Add New Route
        </Button>
      </div>

      {/* Search Bar */}
      <div className="relative max-w-sm">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <Input
          placeholder="Search by Route ID, Warehouse, or Supplier..."
          className="pl-9"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      {/* Routes Table */}
      <Card>
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Route ID</TableHead>
                  <TableHead>Source Warehouse</TableHead>
                  <TableHead>Destination Supplier</TableHead>
                  <TableHead>Distance (km)</TableHead>
                  <TableHead>Vehicle</TableHead>
                  <TableHead>Route Status</TableHead>
                  <TableHead>Delivery ETA</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredRoutes.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={8} className="text-center py-8 text-muted-foreground">
                      No routes found. Create your first route to get started.
                    </TableCell>
                  </TableRow>
                ) : (
                  filteredRoutes.map((route) => (
                    <TableRow key={route.id}>
                      <TableCell className="font-medium">{route.route_id}</TableCell>
                      <TableCell>{route.warehouses?.name || "—"}</TableCell>
                      <TableCell>{route.suppliers?.name || "—"}</TableCell>
                      <TableCell>{route.distance_km ? `${route.distance_km} km` : "—"}</TableCell>
                      <TableCell>{route.vehicle_assigned || "—"}</TableCell>
                      <TableCell>{getStatusBadge(route.route_status)}</TableCell>
                      <TableCell>
                        {route.expected_arrival_time
                          ? format(new Date(route.expected_arrival_time), "MMM dd, yyyy HH:mm")
                          : "—"}
                      </TableCell>
                      <TableCell>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => {
                            setSelectedRoute(route);
                            setIsViewDialogOpen(true);
                          }}
                        >
                          <Eye className="h-4 w-4" />
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>

      {/* Add Dialog */}
      <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Add New Route</DialogTitle>
            <DialogDescription>
              Create a new route between warehouse and supplier
            </DialogDescription>
          </DialogHeader>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              {/* Plan ID */}
              <div className="space-y-2">
                <Label>Plan ID</Label>
                <Select
                  value={formData.plan_id}
                  onValueChange={(value) =>
                    setFormData({ ...formData, plan_id: value })
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select plan (optional)" />
                  </SelectTrigger>
                  <SelectContent>
                    {supplyChainPlans?.map((plan) => (
                      <SelectItem key={plan.plan_id} value={plan.plan_id}>
                        {plan.plan_id} - {plan.po_number || "No PO"}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Source Warehouse */}
              <div className="space-y-2">
                <Label>Source Warehouse *</Label>
                <Select
                  value={formData.source_warehouse_id}
                  onValueChange={(value) =>
                    setFormData({ ...formData, source_warehouse_id: value })
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select warehouse" />
                  </SelectTrigger>
                  <SelectContent>
                    {warehouses?.map((warehouse) => (
                      <SelectItem key={warehouse.id} value={warehouse.id}>
                        {warehouse.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Destination Supplier */}
              <div className="space-y-2">
                <Label>Destination Supplier *</Label>
                <Select
                  value={formData.destination_supplier_id}
                  onValueChange={(value) =>
                    setFormData({ ...formData, destination_supplier_id: value })
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select supplier" />
                  </SelectTrigger>
                  <SelectContent>
                    {suppliers?.map((supplier) => (
                      <SelectItem key={supplier.id} value={supplier.id}>
                        {supplier.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Distance */}
              <div className="space-y-2">
                <Label>Distance (km)</Label>
                <Input
                  type="number"
                  step="0.1"
                  placeholder="Enter distance"
                  value={formData.distance_km}
                  onChange={(e) =>
                    setFormData({ ...formData, distance_km: e.target.value })
                  }
                />
              </div>

              {/* Vehicle Assigned */}
              <div className="space-y-2">
                <Label>Vehicle Assigned</Label>
                <Select
                  value={formData.vehicle_assigned}
                  onValueChange={(value) =>
                    setFormData({ ...formData, vehicle_assigned: value })
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select vehicle" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Van">Van</SelectItem>
                    <SelectItem value="Truck">Truck</SelectItem>
                    <SelectItem value="Container">Container</SelectItem>
                    <SelectItem value="Motorcycle">Motorcycle</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              {/* Departure Time */}
              <div className="space-y-2">
                <Label>Departure Time</Label>
                <Input
                  type="datetime-local"
                  value={formData.departure_time}
                  onChange={(e) =>
                    setFormData({ ...formData, departure_time: e.target.value })
                  }
                />
              </div>

              {/* Expected Arrival Time */}
              <div className="space-y-2">
                <Label>Expected Arrival Time</Label>
                <Input
                  type="datetime-local"
                  value={formData.expected_arrival_time}
                  onChange={(e) =>
                    setFormData({ ...formData, expected_arrival_time: e.target.value })
                  }
                />
              </div>

              {/* Route Status */}
              <div className="space-y-2 col-span-2">
                <Label>Route Status *</Label>
                <Select
                  value={formData.route_status}
                  onValueChange={(value) =>
                    setFormData({ ...formData, route_status: value })
                  }
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="scheduled">Scheduled</SelectItem>
                    <SelectItem value="in_transit">In Transit</SelectItem>
                    <SelectItem value="delivered">Delivered</SelectItem>
                    <SelectItem value="delayed">Delayed</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="flex justify-end space-x-2 pt-4">
              <Button
                type="button"
                variant="outline"
                onClick={() => {
                  setIsAddDialogOpen(false);
                  resetForm();
                }}
              >
                Cancel
              </Button>
              <Button type="submit" disabled={createRouteMutation.isPending}>
                Save Route
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>

      {/* View Dialog */}
      <Dialog open={isViewDialogOpen} onOpenChange={setIsViewDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Route Details</DialogTitle>
          </DialogHeader>

          {selectedRoute && (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Route ID</p>
                  <p className="text-lg font-semibold">{selectedRoute.route_id}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Status</p>
                  <div className="mt-1">{getStatusBadge(selectedRoute.route_status)}</div>
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Source Warehouse</p>
                  <p className="text-lg">{selectedRoute.warehouses?.name}</p>
                  <p className="text-sm text-muted-foreground">{selectedRoute.warehouses?.address}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Destination Supplier</p>
                  <p className="text-lg">{selectedRoute.suppliers?.name}</p>
                  <p className="text-sm text-muted-foreground">{selectedRoute.suppliers?.address}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Distance</p>
                  <p className="text-lg">{selectedRoute.distance_km ? `${selectedRoute.distance_km} km` : "—"}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Vehicle Assigned</p>
                  <p className="text-lg">{selectedRoute.vehicle_assigned || "—"}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Departure Time</p>
                  <p className="text-lg">
                    {selectedRoute.departure_time
                      ? format(new Date(selectedRoute.departure_time), "MMM dd, yyyy HH:mm")
                      : "—"}
                  </p>
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Expected Arrival</p>
                  <p className="text-lg">
                    {selectedRoute.expected_arrival_time
                      ? format(new Date(selectedRoute.expected_arrival_time), "MMM dd, yyyy HH:mm")
                      : "—"}
                  </p>
                </div>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
