import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { Search, Plus, Edit, Eye } from "lucide-react";
import { format } from "date-fns";

export default function SupplyChainPlanning() {
  const queryClient = useQueryClient();
  const [searchTerm, setSearchTerm] = useState("");
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [isViewDialogOpen, setIsViewDialogOpen] = useState(false);
  const [selectedPlan, setSelectedPlan] = useState<any>(null);
  const [formData, setFormData] = useState({
    product_id: "",
    supplier_id: "",
    warehouse_id: "",
    forecast_demand: "",
    plan_status: "pending",
  });

  // Fetch supply chain plans with related data
  const { data: plans, isLoading } = useQuery({
    queryKey: ["supply_chain_plans"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("supply_chain_plans")
        .select(`
          *,
          items (id, name, sku),
          suppliers (id, name),
          warehouses (id, name)
        `)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data;
    },
  });

  // Fetch products from inventory
  const { data: products } = useQuery({
    queryKey: ["inventory_items"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("items")
        .select("*")
        .eq("is_active", true)
        .order("name");
      if (error) throw error;
      return data;
    },
  });

  // Fetch suppliers from procurement
  const { data: suppliers } = useQuery({
    queryKey: ["suppliers"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("suppliers")
        .select("*")
        .order("name");
      if (error) throw error;
      return data;
    },
  });

  // Fetch warehouses from inventory
  const { data: warehouses } = useQuery({
    queryKey: ["warehouses"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("warehouses")
        .select("*")
        .eq("is_active", true)
        .order("name");
      if (error) throw error;
      return data;
    },
  });

  // Get current stock for selected product
  const { data: currentStock } = useQuery({
    queryKey: ["current_stock", formData.product_id],
    queryFn: async () => {
      if (!formData.product_id) return null;

      const { data, error } = await supabase
        .from("inventory")
        .select("quantity")
        .eq("item_id", formData.product_id)
        .maybeSingle();

      if (error) throw error;
      return data?.quantity || 0;
    },
    enabled: !!formData.product_id,
  });

  // Get estimated delivery date from procurement
  const { data: estimatedDelivery } = useQuery({
    queryKey: ["estimated_delivery", formData.supplier_id],
    queryFn: async () => {
      if (!formData.supplier_id) return null;

      const { data, error } = await supabase
        .from("purchase_orders")
        .select("order_date")
        .eq("supplier_id", formData.supplier_id)
        .order("order_date", { ascending: false })
        .limit(1)
        .maybeSingle();

      if (error) throw error;
      
      if (data?.order_date) {
        const orderDate = new Date(data.order_date);
        const estimatedDate = new Date(orderDate);
        estimatedDate.setDate(estimatedDate.getDate() + 7); // Add 7 days as estimate
        return estimatedDate.toISOString().split('T')[0];
      }
      return null;
    },
    enabled: !!formData.supplier_id,
  });

  // Create supply chain plan mutation
  const createPlanMutation = useMutation({
    mutationFn: async (data: any) => {
      const { error } = await supabase
        .from("supply_chain_plans")
        .insert([{
          plan_id: "", // Auto-generated by trigger
          product_id: data.product_id,
          supplier_id: data.supplier_id,
          warehouse_id: data.warehouse_id,
          forecast_demand: parseInt(data.forecast_demand),
          plan_status: data.plan_status,
        }]);

      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("Supply chain plan created successfully");
      queryClient.invalidateQueries({ queryKey: ["supply_chain_plans"] });
      setIsAddDialogOpen(false);
      resetForm();
    },
    onError: (error: any) => {
      toast.error(`Failed to create plan: ${error.message}`);
    },
  });

  // Update supply chain plan mutation
  const updatePlanMutation = useMutation({
    mutationFn: async ({ id, data }: any) => {
      const { error } = await supabase
        .from("supply_chain_plans")
        .update({
          product_id: data.product_id,
          supplier_id: data.supplier_id,
          warehouse_id: data.warehouse_id,
          forecast_demand: parseInt(data.forecast_demand),
          plan_status: data.plan_status,
          updated_at: new Date().toISOString(),
        })
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("Supply chain plan updated successfully");
      queryClient.invalidateQueries({ queryKey: ["supply_chain_plans"] });
      setIsAddDialogOpen(false);
      setSelectedPlan(null);
      resetForm();
    },
    onError: (error: any) => {
      toast.error(`Failed to update plan: ${error.message}`);
    },
  });

  const resetForm = () => {
    setFormData({
      product_id: "",
      supplier_id: "",
      warehouse_id: "",
      forecast_demand: "",
      plan_status: "pending",
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.product_id || !formData.supplier_id || !formData.warehouse_id || !formData.forecast_demand) {
      toast.error("Please fill in all required fields");
      return;
    }

    if (selectedPlan) {
      updatePlanMutation.mutate({ id: selectedPlan.id, data: formData });
    } else {
      createPlanMutation.mutate(formData);
    }
  };

  const handleEdit = (plan: any) => {
    setSelectedPlan(plan);
    setFormData({
      product_id: plan.product_id,
      supplier_id: plan.supplier_id,
      warehouse_id: plan.warehouse_id,
      forecast_demand: plan.forecast_demand.toString(),
      plan_status: plan.plan_status,
    });
    setIsAddDialogOpen(true);
  };

  const filteredPlans = (plans || []).filter((plan) => {
    const search = searchTerm.toLowerCase();
    return (
      plan.plan_id?.toLowerCase().includes(search) ||
      plan.items?.name?.toLowerCase().includes(search) ||
      plan.suppliers?.name?.toLowerCase().includes(search)
    );
  });

  const getStatusBadge = (status: string) => {
    const variants: Record<string, any> = {
      pending: "secondary",
      approved: "default",
      delayed: "destructive",
    };
    return <Badge variant={variants[status] || "outline"}>{status}</Badge>;
  };

  if (isLoading) {
    return <div className="flex items-center justify-center h-64">Loading supply chain plans...</div>;
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-foreground">Supply Chain Planning</h2>
          <p className="text-sm text-muted-foreground">
            Manage supply chain plans with live data from Inventory and Procurement
          </p>
        </div>
        <Button onClick={() => {
          setSelectedPlan(null);
          resetForm();
          setIsAddDialogOpen(true);
        }}>
          <Plus className="h-4 w-4 mr-2" />
          Add New Supply Plan
        </Button>
      </div>

      {/* Search Bar */}
      <div className="relative max-w-sm">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <Input
          placeholder="Search by Plan ID, Product, or Supplier..."
          className="pl-9"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      {/* Plans Table */}
      <Card>
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Plan ID</TableHead>
                  <TableHead>Product</TableHead>
                  <TableHead>Current Stock</TableHead>
                  <TableHead>Supplier</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Warehouse</TableHead>
                  <TableHead>Forecast Demand</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredPlans.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={8} className="text-center py-8 text-muted-foreground">
                      No supply chain plans found. Create your first plan to get started.
                    </TableCell>
                  </TableRow>
                ) : (
                  filteredPlans.map((plan) => (
                    <TableRow key={plan.id}>
                      <TableCell className="font-medium">{plan.plan_id}</TableCell>
                      <TableCell>{plan.items?.name || "—"}</TableCell>
                      <TableCell>
                        {(() => {
                          // Get current stock from inventory
                          const stockQuery = supabase
                            .from("inventory")
                            .select("quantity")
                            .eq("item_id", plan.product_id)
                            .maybeSingle();
                          return "Loading...";
                        })()}
                      </TableCell>
                      <TableCell>{plan.suppliers?.name || "—"}</TableCell>
                      <TableCell>{getStatusBadge(plan.plan_status)}</TableCell>
                      <TableCell>{plan.warehouses?.name || "—"}</TableCell>
                      <TableCell>{plan.forecast_demand} units</TableCell>
                      <TableCell>
                        <div className="flex space-x-2">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => {
                              setSelectedPlan(plan);
                              setIsViewDialogOpen(true);
                            }}
                          >
                            <Eye className="h-4 w-4" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleEdit(plan)}
                          >
                            <Edit className="h-4 w-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>

      {/* Add/Edit Dialog */}
      <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>
              {selectedPlan ? "Edit Supply Plan" : "Add New Supply Plan"}
            </DialogTitle>
            <DialogDescription>
              Create a new supply chain plan by selecting product, supplier, and warehouse.
            </DialogDescription>
          </DialogHeader>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              {/* Product */}
              <div className="space-y-2">
                <Label>Product *</Label>
                <Select
                  value={formData.product_id}
                  onValueChange={(value) =>
                    setFormData({ ...formData, product_id: value })
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select product" />
                  </SelectTrigger>
                  <SelectContent>
                    {products?.map((product) => (
                      <SelectItem key={product.id} value={product.id}>
                        {product.name} ({product.sku})
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Current Stock (Auto Display) */}
              <div className="space-y-2">
                <Label>Current Stock</Label>
                <Input
                  value={currentStock !== null ? `${currentStock} units` : "Select product"}
                  disabled
                  className="bg-muted"
                />
              </div>

              {/* Supplier */}
              <div className="space-y-2">
                <Label>Supplier *</Label>
                <Select
                  value={formData.supplier_id}
                  onValueChange={(value) =>
                    setFormData({ ...formData, supplier_id: value })
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select supplier" />
                  </SelectTrigger>
                  <SelectContent>
                    {suppliers?.map((supplier) => (
                      <SelectItem key={supplier.id} value={supplier.id}>
                        {supplier.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Estimated Delivery Date */}
              <div className="space-y-2">
                <Label>Estimated Delivery Date</Label>
                <Input
                  value={estimatedDelivery || "Select supplier"}
                  disabled
                  className="bg-muted"
                />
              </div>

              {/* Warehouse */}
              <div className="space-y-2">
                <Label>Warehouse Location *</Label>
                <Select
                  value={formData.warehouse_id}
                  onValueChange={(value) =>
                    setFormData({ ...formData, warehouse_id: value })
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select warehouse" />
                  </SelectTrigger>
                  <SelectContent>
                    {warehouses?.map((warehouse) => (
                      <SelectItem key={warehouse.id} value={warehouse.id}>
                        {warehouse.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Forecast Demand */}
              <div className="space-y-2">
                <Label>Forecast Demand (units) *</Label>
                <Input
                  type="number"
                  placeholder="Enter forecast demand"
                  value={formData.forecast_demand}
                  onChange={(e) =>
                    setFormData({ ...formData, forecast_demand: e.target.value })
                  }
                />
              </div>

              {/* Plan Status */}
              <div className="space-y-2 col-span-2">
                <Label>Plan Status *</Label>
                <Select
                  value={formData.plan_status}
                  onValueChange={(value) =>
                    setFormData({ ...formData, plan_status: value })
                  }
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="pending">Pending</SelectItem>
                    <SelectItem value="approved">Approved</SelectItem>
                    <SelectItem value="delayed">Delayed</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="flex justify-end space-x-2 pt-4">
              <Button
                type="button"
                variant="outline"
                onClick={() => {
                  setIsAddDialogOpen(false);
                  setSelectedPlan(null);
                  resetForm();
                }}
              >
                Cancel
              </Button>
              <Button
                type="submit"
                disabled={createPlanMutation.isPending || updatePlanMutation.isPending}
              >
                {selectedPlan ? "Update Plan" : "Save Plan"}
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>

      {/* View Dialog */}
      <Dialog open={isViewDialogOpen} onOpenChange={setIsViewDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Supply Plan Details</DialogTitle>
          </DialogHeader>

          {selectedPlan && (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Plan ID</p>
                  <p className="text-lg font-semibold">{selectedPlan.plan_id}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Product</p>
                  <p className="text-lg">{selectedPlan.items?.name}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Supplier</p>
                  <p className="text-lg">{selectedPlan.suppliers?.name}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Warehouse</p>
                  <p className="text-lg">{selectedPlan.warehouses?.name}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Forecast Demand</p>
                  <p className="text-lg">{selectedPlan.forecast_demand} units</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Status</p>
                  <div className="mt-1">{getStatusBadge(selectedPlan.plan_status)}</div>
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Created At</p>
                  <p className="text-lg">
                    {format(new Date(selectedPlan.created_at), "MMM dd, yyyy")}
                  </p>
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Last Updated</p>
                  <p className="text-lg">
                    {format(new Date(selectedPlan.updated_at), "MMM dd, yyyy")}
                  </p>
                </div>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
