// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpebovspsqxqnyjrmrbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwZWJvdnNwc3F4cW55anJtcmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NjczNDEsImV4cCI6MjA3MzA0MzM0MX0.5BgFWcio9RfA1_mb-P3kI6KNBSOscApZ9p0ki2z2oJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});